version: "3"
services:

  php-fpm:
    container_name: "php-fpm"
    restart: always
    image: php:7.4.33-fpm-alpine
    environment:
      TZ: "Asia/Shanghai"
    # links:
    #   - "go-cqhttp"
    volumes:
      - "/www/wwwroot/website:/usr/share/nginx/html"
      - "/www/wwwroot/config/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "/www/wwwroot/config/php.ini:/usr/local/etc/php/php.ini"

  nginx:
    image: nginx:1.23.3
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php-fpm"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "/www/wwwroot/website:/usr/share/nginx/html"
      - "/www/wwwroot/config/default.conf:/etc/nginx/conf.d/default.conf"

  # go-cqhttp:
  #   image: xiwangly/go-cqhttp:arm64
  #   container_name: "go-cqhttp"
  #   restart: always
  #   ports:
  #     - "5700:5700"
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   volumes:
  #     - "/www/wwwroot/go-cqhttp:/go-cqhttp"
  #    stdin_open: true
  #    tty: true
